### ISSUE TITLE
Does it run under CupertinoApp?

### ISSUE THREAD

**Issue by llorenzo** [Andrious/app_popup_menu#3]
Hi, I'm looking for a popup menu that runs under Cupertino app. The material popup menu needs a material app. But my app is cupertino and it has already advanced some bit...

**Comment by Andrious** [comment]
A Popup menu is a Material concept.  More specifically, the iPhone app does not have such an interface, no?

**Comment by llorenzo** [comment]
Well, I was wandering about the absence for cupertino. The Safari on the iPad has a dropdown menu for sure. Here is a link to a discussion over Dropdown vs. popup menu. https://ux.stackexchange.com/questions/117118/what-is-the-difference-between-popover-menu-drop-down-menu-fly-out-menu

**Comment by Andrious** [comment]
Indeed, it does. 
```
    // If not running under the MaterialApp widget.
    if (context.widget is! Material &&
        context.findAncestorWidgetOfExactType<Material>() == null) {
      popupMenu = Material(child: popupMenu);
    }
```
